// Generated by CoffeeScript 1.3.3

(function($) {
  return $(document).on('mouseover', 'a', function() {
    var a, href, left, o, top;
    $('.link_detect').remove();
    a = $(this);
    href = a.attr('href');
    o = a.offset();
    left = o.left + 20;
    top = o.top + 20;
    return $('<div>').addClass('link_detect').text(href).css({
      'left': left,
      'top': top
    }).appendTo('body');
  });
})(jQuery);
